name: CI - Docker compose project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout code
      uses: actions/checkout@v3

      -name: set up docker
      uses: docker/setup-buildx-action@v3

      -name: Build and start containers
      run: docker compose up -d --build

      -name: Wait for services to be healthy
      run: sleep 10

      -name: Show container status
      run: docker compose ps

      -name: Fail if any container is unhealthy
      run: |
        docker compose ps | grep web | grep -v "Up"

